#pragma once
// Auto-generated by firmware/models/train_model.py
// Date:         2026-04-05T19:33:28Z
// Samples:      10000
// Epochs:       20
// Val accuracy: 0.823
// Val AUC:      0.488
// Threshold (firmware): ANOMALY_THRESHOLD 0.8  (device_config.h)
// To regenerate: python firmware/models/train_model.py --synthetic

extern const unsigned char g_model_data[];
extern const int           g_model_data_len;
